// <auto-generated />
namespace Werzid.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedtransactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtransactions));
        
        string IMigrationMetadata.Id
        {
            get { return "201809122236420_addedtransactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
