// <auto-generated />
namespace Werzid.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedimagepathtoproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedimagepathtoproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201809191401115_addedimagepathtoproduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
